apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: skywalking
spec:
  selector:
    matchLabels:
      app: busybox
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        resources:
          requests:
            cpu: 1000m
#            ephemeral-storage: 100Ki
            memory: 1Gi
          limits:
            cpu: 1000m
#            ephemeral-storage: 100Ki
            memory: 1Gi
        command:
        - sleep
        - "3600"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
